extend_content_security_policy:
  type: list
  default: "script_src: https://unpkg.com/browse/wikipedia-preview@latest/dist/wikipedia-preview.production.js|script_src: https://reftaggercdn.global.ssl.fastly.net|script_src: https://reftagger.bibliacdn.com"
bible_translation:
  type: enum
  default: New American Standard Bible (NASB)
  choices:
  - Amplified Bible (AMP)
  - American Standard Version (ASV)
  - Darby
  - English Standard Version
  - God's Word (GW)
  - Holman Christian Standard Bible (HCSB)
  - King James Version (KJV)
  - Lexham English Bible (LEB)
  - Message Bible
  - New American Standard Bible (NASB)
  - New Century Version (NCV)
  - New International Version (NIV)
  - New International Reader's Version (NIRV)
  - New King James Version (NKJV)
  - New Living Translation (NLT)
  - Douay-Rheims
  - Young's Literal Translation (YLT)
